[pub] mobile main page 퍼블리싱
bsideproject/knit-frontend pull request #147
Opened 2021-08-06 04:15 UTC by Shinsunah

### Changes

PC 및 모바일 메인페이지 퍼블리싱 작업

### Comment

2021-08-10 04:09 UTC, kwonth211 requested changes
사용안하는 css 코드 주석은 과감히 지워주셔도 좋을 것 같습니다.

2021-08-10 04:09 UTC, kwonth211 commented on atoms/layout/header/NavigationBar.styled.ts
> +  @media only screen and (max-width: 768px) {
`@media (max-width: 768px) { `
로 축약 할 수있을 것 같아요

2021-08-10 04:09 UTC, kwonth211 commented on atoms/layout/Layout.tsx
> +      {/* <Contents paddingTopPx={headerHeightPx}>{children}</Contents> */}
주석하신 이유가 어떻게 되나요?

2021-08-10 04:09 UTC, kwonth211 commented on molecules/main/DebateSection/DebateSection.styled.ts
> +    color: #5c16cb !important;
이것도 바꾸신 이유가 있을까요? `${theme.palette.secondary}` 로 변경해주세요

2021-08-10 04:09 UTC, kwonth211 commented on molecules/main/ExtraSection/RecentlyModified.styled.ts
> +  // flex: 1 1 0;
사용 안하는 코드는 모두 지워주세요

2021-08-10 10:45 UTC, Shinsunah commented on atoms/layout/header/NavigationBar.styled.ts
> +  @media only screen and (max-width: 768px) {
네 모두 바꾸겠습니다

2021-08-10 10:51 UTC, Shinsunah commented on molecules/main/DebateSection/DebateSection.styled.ts
> +    color: #5c16cb !important;
이 부분은 roll back 했습니다

2021-08-10 11:24 UTC, kwonth211 commented on molecules/main/DebateSection/DebateSection.styled.ts
> +    color: #5c16cb !important;
rollback이 아닌.. 색상을 맞추려면 secondary로 바뀌어야 하는거 아닌가요?

2021-08-11 07:38 UTC, Shinsunah commented on molecules/main/DebateSection/DebateSection.styled.ts
> +    color: #5c16cb !important;
primary color(#5c16cb)가 맞아요!

2021-08-11 07:38 UTC, Shinsunah commented on molecules/main/ExtraSection/RecentlyModified.styled.ts
> +  // flex: 1 1 0;
넵

2021-08-11 07:40 UTC, kwonth211 commented on atoms/layout/Layout.tsx
> +      {/* <Contents paddingTopPx={headerHeightPx}>{children}</Contents> */}
Contents componen에 paddingTop props를 주입해서 재사용 할 수 있습니다

2021-08-11 07:44 UTC, kwonth211 approved these changes
수고하셨습니다

2021-08-11 07:45 UTC, merged