[Add/UI] refactoring layout page
bsideproject/knit-frontend pull request #16
Opened 2021-02-11 15:55 UTC by kwonth211

### Changes
레이아웃 및 헤더 기본 틀 작업
### Comment
임시로 좀 기본적인 구조만 잡아 놓았습니다. 
별로인 부분은 피드백 부탁드려요 
TempLogo -> 삭제 예정
Container Component -> 가운데 정렬용

2021-02-11 16:30 UTC, liebebe requested changes

2021-02-11 16:30 UTC, liebebe commented on features/container/Container.tsx
> +}
이 컴포넌트가 하는 역할이 가운데 정렬 밖에 없는 건가요? 만약 그렇다면 컴포넌트로 따로 만들 필요 없이 sass mixin으로 처리할 수 있지 않을까 싶습니다.

2021-02-11 16:30 UTC, liebebe commented on features/header/Header.tsx
>  }
조금 애매하기는 한데 Header 컴포넌트를 layout feature 하위에 두는게 더 좋지 않을까요? header feature를 따로 두어야 할만큼 여러종류의 XxxHeader가 정의될 것 같지 않기도 하고, Header를 page 컴포넌트에서 직접 import하여 사용하기보다 실제적으로 사용하는 곳이 Layout 컴포넌트 뿐일 것 같아서 layout 하위에 같이 위치시키는게 좋지 않을까하는 생각이 듭니다.

2021-02-11 16:30 UTC, liebebe commented on pages/signin.tsx
>  }
라우팅할때마다 `Layout` 컴포넌트를 다시 그리지 않게 `App` 컴포넌트에 마운트시키는 것이 좋을 것 같습니다.

```ts
// app/index.tsx
function App({ Component, pageProps }: AppProps) {
  return (
    <Layout>
      <Component {...pageProps} />
    </Layout>
  );
}
```

2021-02-12 00:02 UTC, kwonth211 commented on features/container/Container.tsx
> +}
가운데 정렬이라기 보다는 
![image](https://user-images.githubusercontent.com/47585977/107714563-da0b2580-6d10-11eb-8858-eb2f1b336c03.png)
안쪽 여백에 해당하는 부분인데요.  표현을 잘 못한듯 하네요 
외부 width 100% 인 부모가 있고  container는 max-width의 내부 영역입니다.

2021-02-12 00:04 UTC, kwonth211 commented on features/container/Container.tsx
> +}
![image](https://user-images.githubusercontent.com/47585977/107714770-2eaea080-6d11-11eb-8330-394237be554a.png)

가운데 정렬이라기 보다는 안쪽 여백에 해당하는 부분인데요. 표현을 잘 못한듯 하네요
외부 width 100% 인 부모가 있고 container는 max-width의 내부 영역입니다.

2021-02-12 00:04 UTC, kwonth211 commented on features/header/Header.tsx
>  }
좋은 아이디어 인것 같습니다

2021-02-12 00:10 UTC, kwonth211 commented on pages/signin.tsx
>  }
흠.. 그래도 _app 으로 변경하는게 좋을듯 하네요

2021-02-12 00:18 UTC, kwonth211 commented on pages/signin.tsx
>  }
오히려 더 많은 렌더링을 초래하게 되는거 같아요 App 으로 바꿨더니

2021-02-12 00:38 UTC, kwonth211 commented on pages/signin.tsx
>  }
그래도 Layout은 App안에서 그려지는게 더 안정감 있는 패턴인 것 같아서 변경 했습니다

2021-02-12 00:43 UTC, liebebe commented on pages/signin.tsx
>  }
음 오히려 랜더링을 더 많이하게 되나요? Next의 App이 일반적인 리액트 컴포넌트 랜더링 프로세스랑은 다른가보네요..

2021-02-12 00:44 UTC, liebebe commented on features/container/Container.tsx
> +}
음 그래도 여전히 scss variable로 처리할 수 있지 않을까 하는 생각이 드는데, 굳이 컴포넌트로 두어야 한다고 하면 layout feature 하위로 이동시키는 게 좋을 것 같습니다.

2021-02-12 01:01 UTC, liebebe approved these changes

2021-02-12 01:02 UTC, kwonth211 commented on features/container/Container.tsx
> +}
네 무슨말씀인지는 알거같은데요, 규모가 점점 커진다면 명확히 분리시켜야 유지보수 측면에서도 편할 것 같아요. 
layout feature에만 옮겨 놓을게요

2021-02-12 02:14 UTC, liebebe approved these changes
수고하셨습니다.

2021-02-12 02:31 UTC, merged