문서 편집 / 직군, 주제태그 편집
bsideproject/knit-frontend pull request #97
Opened 2021-04-07 18:48 UTC by liebebe

### Changes
- 문서 편집 / 직군, 주제태그 수정 기능 추가하였습니다.

#### 직군 수정

![image](https://user-images.githubusercontent.com/34727284/113917489-39227d80-981c-11eb-9d1c-b609a8c34534.png)

- 아이콘 클릭 시 선택/해제
- 선택된 경우 아이콘 테두리 강조

#### 주제태그 수정

![image](https://user-images.githubusercontent.com/34727284/113917533-47709980-981c-11eb-917a-f800332f916a.png)

- 주제태그 영역 클릭 시 **주제태그 수정 가능한 상태**로 전환
- **주제태그 수정 가능한 상태**로 진입 시 **새 주제태그 입력 영역** 노출
- **새 주제태그 입력 영역** 내 입력한 값이 있는 상태에서 enter 입력 시 주제태그 추가
- **주제태그 수정 가능한 상태**에서 기존 주제태그에 마우스 hover시 삭제버튼 노출
- **주제태그 수정 가능한 상태**에서 주제태그 외부 영역 클릭 시 **주제태그 수정 불가능한 상태**로 전환 
- **주제태그 수정 가능한 상태**에서 esc 입력 시 **주제태그 수정 불가능한 상태**로 전환 

### Comment
- 혹시 PR 생성할 때 전송되는 알람이 소리를 동반하지는 않으시죠..? 새벽에 자꾸 PR 올리게 되는데 혹시나 수면을 방해할까봐 여쭤봅니다.

2021-04-07 23:59 UTC, kwonth211 commented
네 ㅎㅎ 저는 평상시에도 무음모드라 괜찮습니다 😴

2021-04-08 00:32 UTC, kwonth211 requested changes

2021-04-08 00:32 UTC, kwonth211 commented on .eslintrc.js
> +        'react/no-array-index-key': 'warn',
해당 lint 는 필수로 해도 괜찮지 않을까요??

2021-04-08 00:32 UTC, kwonth211 commented on molecules/main/SearchBanner.styled.ts
> +import { Tag as ATag } from '~/atoms/tag';
처음 사용하셨던 것처럼 AtomTag로 명명규칙을 정하는게 좋을 것 같아요

2021-04-08 00:32 UTC, kwonth211 commented on molecules/thread/Tags/Tag.styled.ts
> +  & > ${Tag} {
저번에도 궁금했었는데 컴포넌트를 선택자로 잡으면 어떠한 이점이 있나요?

2021-04-09 02:34 UTC, liebebe commented on .eslintrc.js
> +        'react/no-array-index-key': 'warn',
종종 어레이 인덱스를 key로 쓰는게 합리적인 케이스(어레이 내 아이템의 순서가 전혀 변경될 일이 없고 각 아이템이 unique한 property를 가지고 있지 않은 경우)가 있어서 warn 으로 변경하였습니다.

2021-04-09 02:37 UTC, liebebe commented on molecules/main/SearchBanner.styled.ts
> +import { Tag as ATag } from '~/atoms/tag';
태훈님 코드 보고 명명규칙 맞추려고 따라한건데 다시 찾아보려고 하니까 없네요. 제가 잘못봤나봅니다. 수정하도록 하겠습니다.

2021-04-09 02:40 UTC, liebebe commented on molecules/thread/Tags/Tag.styled.ts
> +  & > ${Tag} {
위의 코드를 예로 설명드리면 Tag의 기본 스타일은 유지한 체 Container 이하에 위치하는 경우의 스타일을 부여해줄 수 있습니다. 스타일을 오버라이드하는 느낌으로 사용이 가능합니다.

2021-04-09 02:42 UTC, kwonth211 commented on molecules/main/SearchBanner.styled.ts
> +import { Tag as ATag } from '~/atoms/tag';
아 Antdesign aslias 를 Axxx 로 정하긴 했었는데요. 다음에 뭐 AntdXXX로 수정하도록 하겠습니다

2021-04-09 02:45 UTC, kwonth211 commented on molecules/thread/Tags/Tag.styled.ts
> +  & > ${Tag} {
오 ! 그렇군요 감사합니다

2021-04-09 02:46 UTC, kwonth211 submitted a review, later dismissed
💯

2021-04-09 04:08 UTC, liebebe commented on molecules/main/SearchBanner.styled.ts
> +import { Tag as ATag } from '~/atoms/tag';
https://github.com/bsideproject/knit-frontend/pull/97/commits/13b21d0aa072444e75849e2a1fd15d8ddfb24da8 로 수정하였습니다!

2021-04-09 04:09 UTC, merged